[Qt%20Factory%20Cache%204.4]
com.trolltech.Qt.QSqlDriverFactoryInterface%3A\usr\local\qtopia\plugins\sqldrivers\libqsqlite.so=2010-12-12T21:28:08, QSQLITE

[Qt%20Plugin%20Cache%204.4.false]
usr\local\qtopia\plugins\sqldrivers\libqsqlite.so=40400, 0, arm linux g++-4 full-config, 2010-12-12T21:28:08
