[data files]
path=C:\BandG\Deckman\Data
logdir=C:\BandG\Deckman\Log

[comms]
port=0,9600,N,8,1,0
aisport=1,38400,N,8,1,0
servername=10.10.72.10
TCPTimeout=30
;obport=1,9600,N,8,1,0
;laser=2,9600,N,8,1,0
;comgps=7,4800,N,8,1,0

[livechart]
path=C:\BandG\Deckman\Livechart
palette=1
dongleloaded=0
localknowledge=0
VERScode=c4f51dcb3b9265bf
;VERScode=408aaa22fa58d467
useMapTech=0
showMTOutlines=0

[AIS]
Enabled=0
ShowVectors=0
VectorLength=15

[dongle]
type=4

[Euronav]
mode=0
[polars]
perfpol1=C:\BandG\Deckman\Data\Vayu perfpol 2024.d
startpol1=C:\BandG\Deckman\Data\Mahon Start Polar 2023.d
navpol1=C:\BandG\Deckman\Data\Vayu navpol 2023.d
perfpol2=C:\BandG\Deckman\Data\Vayu perfpol 2023.d
adjvt1=C:\BandG\Deckman\Data\Adjvtelv.d
adjwa1=C:\BandG\Deckman\Data\adjstrwaelv.d
stadjvt1=C:\BandG\Deckman\Data\adjstrvt.d
stadjwa1=C:\BandG\Deckman\Data\adjstrwa.d
adjwa2=C:\BandG\Deckman\Data\AdjwaOctansValencia.d
adjwa3=C:\BandG\Deckman\Data\Adjwazero.d
adjvt2=C:\BandG\Deckman\Data\Adjvt_0kn.d
adjwa4=C:\BandG\Deckman\Data\AdjwaOctansPortals.d
adjwa5=C:\BandG\Deckman\Data\AdjwaOctansPortals.d
adjwa6=C:\BandG\Deckman\Data\AdjwaOctansNewport.d
adjvt3=C:\BandG\Deckman\Data\Adjvt.d

[network]
LastLocalIP=10.10.72.20
WTPGrp=234.1.1.1
svrudpport=5602
NavServer=0
