[data files]
path=C:\Program Files (x86)\BandG\Deckman C-Map\Data
logdir=C:\Program Files (x86)\BandG\Deckman C-Map\Log

[comms]
port=0,9600,N,8,1,0
aisport=1,38400,N,8,1,0
servername=192.168.0.2
TCPTimeout=60
;obport=1,9600,N,8,1,0
;laser=2,9600,N,8,1,0
;comgps=7,4800,N,8,1,0

[livechart]
path=C:\Program Files (x86)\BandG\Deckman C-Map\Livechart
palette=0
dongleloaded=0
localknowledge=0
VERScode=408aaa22fa58d467
useMapTech=0

[AIS]
Enabled=0
ShowVectors=0
VectorLength=15

[dongle]
type=3

[Euronav]
mode=0
[polars]
perfpol1=C:\FmData\Wtp3_Perfpol.d
startpol1=C:\FmData\Wtp3_StartPol.d
navpol1=C:\FmData\Wtp3_Perfpol.d
adjvt1=C:\Program Files (x86)\BandG\Deckman C-Map\Data\adjvt.d
adjwa1=C:\Program Files (x86)\BandG\Deckman C-Map\Data\adjwa.d
stadjvt1=C:\Program Files (x86)\BandG\Deckman C-Map\Data\adjvt.d
stadjwa1=C:\Program Files (x86)\BandG\Deckman C-Map\Data\adjwa.d
navpol2=C:\FmData\Wtp3_Navpol.d
navpol3=C:\Program Files (x86)\BandG\Deckman C-Map\Data\navpol.d
perfpol2=C:\Program Files (x86)\BandG\Deckman C-Map\Data\perfpol.d
startpol2=C:\FmData\Wtp3_Perfpol.d
startpol3=C:\Program Files (x86)\BandG\Deckman C-Map\Data\startpol.d
[network]
LastLocalIP=192.168.0.3
WTPGrp=234.1.1.1
svrudpport=5602
NavServer=1
